	
@startuml backend_components



database "SQLite3" {
  folder "Users" {
    [Users table]
  }
  
}


package "API endpoints" {
    folder "Users endpoints" {
        [user creation]
        [user authentication]
        [reset user password]
    }
    folder "White board data endpoints" {
        [data API]
    }
}

database "JSON File" {
  frame "White board data" {
    [white board data]
  }
}

' User API
[user creation] <-- [Users table]
[user authentication] <-- [Users table]
[reset user password] <-- [Users table]

' White board data
[data API] --> [white board data]



@enduml